### ISSUE TITLE
screen flickering on every key stroke on mac sierra [version: 0.33-rc1]

### ISSUE THREAD

**Issue by arooni** [alacritty/alacritty#2684]
Which operating system does the issue occur on?
mac sierra: 10.14.5 (18F132)

If on linux, are you using X11 or Wayland?

alacritty 0.3.3-rc1

video of what i'm talking about: https://youtu.be/l2RI3Qj2fak

I happen to be using tmux in this but it happens regardless of app

**Comment by kchibisov** [comment]
@arooni Can you reproduce this on the latest master or at least on `0.3.3` (you're on prerelease version atm)?

**Comment by chrisduerr** [comment]
Would also be interesting to see if this happens with the default config or only with a modified one.

**Comment by arooni** [comment]
It doesn't happen immediately upon launch it happens after running alacritty after awhile.  I upgraded to 0.3.3 and will report back if I can repro it.

**Comment by tompi** [comment]
This happened to me today after I disconnected my mac(I always have alacritty running on separate display), when I continued without this screen connected, the flickering started.

I can try to repro tomorrow.(v0.3.3)

**Comment by chrisduerr** [comment]
> I can try to repro tomorrow.(v0.3.3)

Please test the latest release, everything else wouldn't be of much use.

**Comment by mrutyunjayan** [comment]
I'm getting the same issue on Catalina

**Comment by chrisduerr** [comment]
@mrutyunjayan Which Alacritty version?

**Comment by mrutyunjayan** [comment]
> @mrutyunjayan Which Alacritty version?

Hi sorry,
 I installed with homebrew...version 0.4.3

**Comment by chrisduerr** [comment]
And the behavior is exactly the same as the linked video?

**Comment by mrutyunjayan** [comment]
> And the behavior is exactly the same as the linked video?

Yup.

Screen flickers as I type.

I can temporarily fix it by force quitting and opening some other app and then coming back to alacrittty.

**Comment by chrisduerr** [comment]
What hardware are you using and does this also only appear after a certain time? What is your opacity set to?

**Comment by mrutyunjayan** [comment]
> What hardware are you using and does this also only appear after a certain time? What is your opacity set to?

I'm on an i5 iMac 2019, rx580, 32gb ram.

I'm not on the computer now so I can't check the opacity, but I'll get back to you on that as soon as I can.

The issue happens as soon as I start up alacritty.

**Comment by chrisduerr** [comment]
It would also be interesting to see if this happens when selecting things too. And please make sure to test outside of tmux.

**Comment by mrutyunjayan** [comment]
> It would also be interesting to see if this happens when selecting things too. And please make sure to test outside of tmux.

How do I test outside of tmux?

**Comment by chrisduerr** [comment]
You exit tmux and type stuff?

**Comment by mrutyunjayan** [comment]
> You exit tmux and type stuff?

Lol sorry I have no idea what tmux is

**Comment by chrisduerr** [comment]
Then you're probably good to go. Tmux is a multiplexer for having multiple shell sessions in one terminal.

**Comment by mrutyunjayan** [comment]
> > What hardware are you using and does this also only appear after a certain time? What is your opacity set to?
> 
> I'm on an i5 iMac 2019, rx580, 32gb ram.
> 
> I'm not on the computer now so I can't check the opacity, but I'll get back to you on that as soon as I can.
> 
> The issue happens as soon as I start up alacritty.

hi my opacity is set to 1.0

**Comment by chrisduerr** [comment]
> It doesn't happen immediately upon launch it happens after running alacritty after awhile. I upgraded to 0.3.3 and will report back if I can repro it.

Since there has been no reply, I'd assume this issue has been resolved.

**Comment by sidmadala** [comment]
I get this issue on nearly every startup with Alacritty 0.6.0 (04cbf76) on MacOS Catalina 10.15.4. Requires multiple attempts at quitting and restarting the application.

**Comment by boeserwolf** [comment]
Same over here on MacOS Cataline 10.15.7 with Alacritty 0.6.0 (04cbf76, Homebrew installation). It happens after ending power saving mode, f. e. by pressing a keystroke, and can be resolved by restarting Alacritty. I'm also having transparency enabled.

**Comment by peteyycz** [comment]
Same here on BigSur. Happens on every launch, transparency enabled.

**Comment by gsa9** [comment]
Same here on BigSur, with MacBook Air M1. It happens after I turn off, then back on, my external monitor.

**Comment by flouc001** [comment]
@chrisduerr - Can we please re-open this issue?

It doesn't appear to have been resolved, I'm experiencing this with:
Alacritty v0.9.0
Macbook Pro - Intel Core i9
Full opacity background

**Comment by rajashekar007** [comment]
Yes, even I happen to notice the screen flickering on each keystroke. I'm using Macbook Pro-M1, BigSur. It disappeared after I close and open the app.

**Comment by dt665m** [comment]
I believe this should be reopened.  M1 Mac, alacritty 0.11.0-dev (b16fe125) and MacOS 12.2.1.  This flickering happens when waking the OS from sleep/suspend.

**Comment by qubbit** [comment]
This happens for me as well. It seems pretty abrupt, as I haven't changed any config.

**Comment by dt665m** [comment]
Still happening... except it's worse on my new install.  Now it just flickers when the app is loaded.  Can this be reopened?
- M1 Mac OSX Ventura 13.1
- Built using "make app"
- alacritty 0.12.0-dev (507f7277)

**Comment by tiagonbotelho** [comment]
Also seem to be observing this behaviour on my M1 Mac OSX Ventura with Alacritty's version being `0.11.0`

**Comment by cosmojg** [comment]
I'm experiencing the same issue right now with `alacritty 0.11.0 (8dbaa0b)` on `macOS Ventura (13.1)`. I've been running Alacritty for a few days now, connecting and disconnecting from external displays multiple times throughout, lining up with the pathology alluded to by @arooni and @tompi above.

As a test, I just tried reconnecting and disconnecting an external display again, and the issue disappeared.

@chrisduerr This is definitely a low-priority bug, but I think it's worth reopening the issue.

**Comment by gugu91** [comment]
Also experiencing this:
- alacritty 0.10.1 (2844606)
- macOS Venture (13.1)
- Apple Silicon
- Using external monitor
- Minimising and maximising "fixes" the issue

**Comment by gerryhernandez** [comment]
I've never experienced this until today, which happens to be the first time I've run Alacritty on my Mac with an external monitor. This happens with and without tmux. I'll try to drop some (hopefully) helpful information in here.

## System info:
Alacritty:
```
❯ alacritty -V
alacritty 0.11.0 (8dbaa0b)
```

Machine:
```
OS: macOS 13.2.1 22D68 x86_64
Host: MacBookPro16,1
Kernel: 22.3.0
Uptime: 7 days, 4 hours, 3 mins
Packages: 36 (port), 140 (brew)
Shell: zsh 5.9
Resolution: 3008x1692@2x, 2048x1280@2x
DE: Aqua
WM: yabai
Terminal: tmux
CPU: Intel i9-9980HK (16) @ 2.40GHz
GPU: Intel UHD Graphics 630, AMD Radeon Pro 5500M
Memory: 25086MiB / 65536MiB
```

## Reproduction steps:
1. Close all Alacritty processes to start from a fresh state.
2. Disconnect external monitor, if connected.
3. Open an Alacritty instance.
4. Plug in external monitor.
5. Move Alacritty to external monitor.
6. Press some keys - anything that causes drawing.

It's especially noticeable in any kind of scrollable buffer such as Vim, Less, etc.

## Workaround
Kill all Alacritty instances and reopen. Seems to work fine after that *so far.*
