### ISSUE TITLE
How to change the cursor color when selecting text in TMUX?

### ISSUE THREAD

**Issue by npearson72** [alacritty/alacritty#4576]
I've been trying Alacritty for about a year now, and in the last couple of months noticed a change in the way text selection looks while in TMUX. For some reason, the last character does not appear to get selected (although it clearly is as it's being copied to my clipboard).

I can't narrow down if it's an issue with Alacritty or TMUX or both, and as such, I've also posted this issue in TMUX: https://github.com/tmux/tmux/issues/2504

I'm attaching a screenshot to demonstrate the problem:

![Kapture 2020-12-15 at 21 29 56](https://user-images.githubusercontent.com/1323414/102276113-08e26680-3f2f-11eb-9f9c-5efd2b102f7d.gif)

Also, my `alacritty.yml` file:

```
window:
  startup_mode: SimpleFullscreen
  decorations: none
  padding:
    x: 5
    y: 0

font:
  size: 14
  normal:
    family: Hack Nerd Font Mono
    style: Regular
  bold:
    family: Hack Nerd Font Mono
    style: Bold
  italic:
    family: Hack Nerd Font Mono
    style: Italic
  offset:
    x: 0
    y: 3

  use_thin_strokes: true

colors:
 # Default Colors
 primary:
   background: '#212121'
   foreground: '#f1f1f1'
 # Normal colors
 normal:
   black:   '#212121'
   red:     '#c30771'
   green:   '#10a778'
   yellow:  '#a89c14'
   blue:    '#008ec4'
   magenta: '#523c79'
   cyan:    '#20a5ba'
   white:   '#f1f1f1'
 # Bright colors
 bright:
   black:   '#424242'
   red:     '#e32791'
   green:   '#5fd7a7'
   yellow:  '#f3e430'
   blue:    '#b6d6fd'
   magenta: '#6855de'
   cyan:    '#4fb8cc'
   white:   '#ffffff'

 cursor:
   text: '#f3f3f3'
   cursor: '#1ac7fc'

# background_opacity: 0.99

bell:
  duration: 10
  color: '#626262'

# Use `xxd -psd` to discover other chars hex values
key_bindings:
  - { key: H,         mods: Alt,        chars: "\x1b\x68" }
  - { key: J,         mods: Alt,        chars: "\x1b\x6a" }
  - { key: K,         mods: Alt,        chars: "\x1b\x6b" }
  - { key: K,         mods: Command,    chars: "\x1C"     } # See .tmux.conf
  - { key: L,         mods: Alt,        chars: "\x1b\x6c" }
  - { key: O,         mods: Alt,        chars: "\x1b\x6f" }
  - { key: R,         mods: Shift|Alt,  chars: "\x1b\x52" }
  - { key: R,         mods: Alt,        chars: "\x1b\x72" }
  - { key: S,         mods: Alt,        chars: "\x1b\x73" }
  - { key: T,         mods: Alt,        chars: "\x1b\x74" }
  - { key: W,         mods: Alt,        chars: "\x1b\x77" }
  - { key: Backslash, mods: Shift|Alt,  chars: "\x1b\x7c" }
  - { key: Minus,     mods: Shift|Alt,  chars: "\x1b\x5f" }
  - { key: LBracket,  mods: Alt,        chars: "\x1b\x5b" }
  - { key: RBracket,  mods: Alt,        chars: "\x1b\x5d" }
  - { key: Semicolon, mods: Shift|Alt,  chars: "\x1b\x3a" }
  - { key: Slash,     mods: Alt,        chars: "\x1b\x2f" }

  - {
      key: N,
      mods: Command,
      command: {
        program: "open",
        args: ["-n", "/Applications/Alacritty.app"]
      }
    }

  - {
      key: Return,
      mods: Command,
      action: ToggleSimpleFullscreen
    }
```

Any ideas on why this might be happening?

### System

OS: macOS
Version: `alacritty 0.6.0 (04cbf76)`

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

I've run `alacritty -vv` and here is the output:

```
[2020-12-15 23:36:09.985459000] [DEBUG] [alacritty] Using environment locale: en_US.UTF-8
[2020-12-15 23:36:09.985630000] [INFO ] [alacritty] Welcome to Alacritty
[2020-12-15 23:36:09.985659000] [INFO ] [alacritty] Configuration files loaded from:
[2020-12-15 23:36:09.985682000] [INFO ] [alacritty]   "/Users/nathan/.config/alacritty/alacritty.yml"
[2020-12-15 23:36:10.031411000] [DEBUG] [alacritty] Estimated DPR: 2
[2020-12-15 23:36:10.031481000] [DEBUG] [alacritty] Estimated window size: None
[2020-12-15 23:36:10.031505000] [DEBUG] [alacritty] Estimated cell size: 16 x 36
[2020-12-15 23:36:11.940867000] [INFO ] [alacritty] Device pixel ratio: 2
[2020-12-15 23:36:11.944234000] [INFO ] [alacritty] Initializing glyph cache...
[2020-12-15 23:36:11.968848000] [INFO ] [alacritty] ... finished initializing glyph cache in 0.02446039s
[2020-12-15 23:36:11.968967000] [INFO ] [alacritty] Cell size: 16 x 36
[2020-12-15 23:36:11.969006000] [INFO ] [alacritty] Padding: 10 x 0
[2020-12-15 23:36:11.969033000] [INFO ] [alacritty] Width: 1600, Height: 1200
[2020-12-15 23:36:11.993743000] [INFO ] [alacritty] PTY dimensions: Line(33) x Column(98)
[2020-12-15 23:36:11.997431000] [INFO ] [alacritty] Initialisation complete
[2020-12-15 23:36:12.026676000] [DEBUG] [alacritty_terminal] New num_cols is 190 and num_lines is 53
[2020-12-15 23:36:12.029329000] [INFO ] [alacritty] Padding: 10 x 0
[2020-12-15 23:36:12.029409000] [INFO ] [alacritty] Width: 3072, Height: 1920
```

**Comment by kchibisov** [comment]
The last cell is a cursor in tmux, so it's selected afaics.

**Comment by chrisduerr** [comment]
Tmux moves your cursor around to select the text and the last cell is just the cursor which is inverted because that's the cursor you selected in Alacritty. It might be questionable why tmux does it this way, but I don't see anything wrong with Alacritty's behavior here. You might be able to configure that in tmux though.

**Comment by npearson72** [comment]
@kchibisov and @chrisduerr thanks for the reply.

I've noticed that in Mac Terminal the cursor is blue. I understand you're saying this is an issue with TMUX or my TMUX configs, but might you be able help shed light on with it's different in Terminal?

### Example:

![Kapture 2020-12-15 at 23 47 42](https://user-images.githubusercontent.com/1323414/102277012-5a3f2580-3f30-11eb-8579-452cc2b52582.gif)

**Comment by kchibisov** [comment]
Maybe its our contrast logic inverts it? Was it happening with 0.5.0?

**Comment by npearson72** [comment]
I don't think it was. I only noticed it in the last month or two (maybe more).

**Comment by npearson72** [comment]
I just tried disabling all my configs, colors, etc... and the problem still persists.

Is there a way to define a different color just for the cursor or to disable the contrast logic for the cursor?

Btw, this issue seems similar to: https://github.com/alacritty/alacritty/issues/2398

**Comment by chrisduerr** [comment]
Actually thanks for the hint @kchibisov, I missed the cursor color in the config.

I believe this is a bug in our contrast logic, where we check the constrast against the cell color and ignore the text color of the cursor. If the cursor foreground is fixed, we shouldn't invert based on cell foreground.

**Comment by chrisduerr** [comment]
Should be fixed in https://github.com/alacritty/alacritty/pull/4577.

**Comment by npearson72** [comment]
Hey @chrisduerr you're awesome! I just confirmed your fix in https://github.com/alacritty/alacritty/pull/4577 works. Thank you.

**Comment by dalizard** [comment]
@npearson72 Has this problem reappeared for you? 🤔 I am running alacritty 0.7.2 and I have the same issue even with your config file.

**Comment by npearson72** [comment]
Yeah, I'm afraid it's reappeared. I've just learned to live with it.

**Comment by krafts** [comment]
Running into the same issue. When the cursor is changed to `Underline` or `Beam` this issues does not appear.

**Comment by m1027** [comment]
I come up with the following solution.

Using tmux >= 3.2 + alacritty.

Summary of the overlapping issues I noticed so far:

(1) tmux without alacritty can select areas including the cursor quite
perfectly.

(2) tmux plus alacritty seems to cause kind of a "double-invert effect" of the
cursor, so in a selection, everything looks inverted (looks like beeing
visually selected) besides the cursor itself.

(3) At least tmux 3.2 has "set mode-style".

(4) Avoiding inverse / reverse: I was trying to find a fg/bg colorset that
does not require inverting: However, when playing with mode-style fg/bg
colors, there are colors the flip the cursor into non-inverse appearence while
others do. I have not investigated why exactly.

(5) Optional: If you want the selection being done by other effects than
inverting fg/bg, you may choose to add e.g. the underline mode-style (not in
my case here).

So, have a look at what I tried out. The final line looks very well here:
Selection is gray, and the cursor itself looks selected, too.

```
#
# better colors for selected regions
#
#set -g mode-style 'bg=black,fg=yellow,noreverse'
#set -g mode-style 'bg=yellow,fg=black,noreverse,underscore'
#set -g mode-style 'bg=red,fg=black,noreverse,underscore'
#set -g mode-style 'bg=black,fg=yellow,noreverse,underscore'
#set -g mode-style 'bg=red,fg=yellow,noreverse,underscore'
#set -g mode-style 'bg=red,fg=yellow,noreverse'
#set -g mode-style 'bg=blue,fg=yellow,noreverse'
#set -g mode-style 'bg=white,fg=black,noreverse'
#set -g mode-style 'bg=yellow,fg=black,noreverse'
set -g mode-style 'bg=#444444,fg=#777777,noreverse'
```

**Comment by chrisduerr** [comment]
The contrast logic has been removed, so this bug should be fixed.

**Comment by npearson72** [comment]
> The contrast logic has been removed, so this bug should be fixed.

In which version? I'm on `alacritty: 0.8.0` and the problem continues.

**Comment by chrisduerr** [comment]
The latest master (0.10.0-dev d8a98f88295e59d6518ae780a9857c033a83161c+).

**Comment by ranelpadon** [comment]
I'm using `alacritty 0.10.0` but the issue is still there, and seems to depend on the contrast threshold of the color scheme being used and needs an intermediate color that is not part of the theme/color scheme.

Thanks to @m1027, got the idea of a workaround, and the resulting selection/cursor colors are now quite acceptable for me:

`set -g mode-style 'bg=#d19a66,fg=#52565c,noreverse'`

<img width="194" alt="Screen Shot 2022-04-26 at 2 14 22 PM" src="https://user-images.githubusercontent.com/4292088/165234121-b240de95-95dc-4c5f-9d9f-ae3b68f108f1.png">

**Comment by isak102** [comment]
This problem still exists and I am on version `alacritty 0.13.1 (fe2a3c56)`

**Comment by kanna5** [comment]
The default cursor color in Alacritty is the reverse of the cell color (see the [documentation](https://alacritty.org/releases/0.15.1/config-alacritty.html#s36)). When selecting text in tmux, the cursor color becomes the inverse of the selection color you set in tmux, making it hard to distinguish from normal text. I found that explicitly setting the cursor color in Alacritty’s config fixes this issue for me.

For example, if you have

```toml
[colors.primary]
background = "#1d2021"
foreground = "#ebdbb2"
```

set

```toml
[colors.cursor]
text = "#1d2021"
cursor = "#ebdbb2"
```
