### ISSUE TITLE
Problem with xmodmap and caps lock.

### ISSUE THREAD

**Issue by deft01** [alacritty/alacritty#4622]
### System

OS: Debian10
Version: 0.7.0-dev (12fbd00)
Linux/BSD: X11, i3wm

### Prelude

Hello guys, I have some trouble with my xmodmap configuration and maybe the caps lock key support.
When I combine my xmodmap shortcut with Ctrl it fail. I added the tests I have made in [Terminator](https://terminator-gtk3.readthedocs.io/en/latest/) as witness tests.
I do my test with the command `showkey -a`. My keyboard layout is dvorak.
I verified that my alacritty.yml is well loaded and it has no shorcuts in it (an almost empty config file).

This is my xmodmap configuration :
```	
        ! -*- coding: utf-8 -*-
	! presonnal layout keyboard script

	! arrows addidion
	keycode 66 = Mode_switch
	! keycode 64 = Mode_switch
	keysym h = h H Left
	keysym n = n N Right
	keysym c = c C Up
	keysym t = t T Down

	! end up addition
	keysym r = r R End
	keysym g = g G Home
	keysym l = l L Delete
```
### Xmodmap arrows shortcuts working well in Terminator and Alacritty
Alacritty is working well for left, up, right and down xmodmap mappings.
As you can see a Terminator test (where everything is working well)
```
^[[A 	 27 0033 0x1b
 	 91 0133 0x5b
 	 65 0101 0x41
^[[B 	 27 0033 0x1b
 	 91 0133 0x5b
 	 66 0102 0x42
^[[D 	 27 0033 0x1b
 	 91 0133 0x5b
 	 68 0104 0x44
^[[C 	 27 0033 0x1b
 	 91 0133 0x5b
 	 67 0103 0x43
```
**Alacritty output for the same keys working well too:**
![image](https://user-images.githubusercontent.com/10063471/103299289-78ab2380-49fc-11eb-968d-739c7c9cc233.png)

### Problem : Ctrl key combined Xmodmap shorcuts are working well in Terminator but not in Alacritty

Now the problem is comming when i try to combine the left and right xmodmap shortcuts with the Ctrl key (to jump words instead for letters).
**On terminator this is working well as you can see :**
```
^[[1;5D 	 27 0033 0x1b
 	 91 0133 0x5b
 	 49 0061 0x31
 	 59 0073 0x3b
 	 53 0065 0x35
 	 68 0104 0x44
^[[1;5C 	 27 0033 0x1b
 	 91 0133 0x5b
 	 49 0061 0x31
 	 59 0073 0x3b
 	 53 0065 0x35
 	 67 0103 0x43
```

**But in Alacritty it is not doing the job :**
![image](https://user-images.githubusercontent.com/10063471/103299475-eb1c0380-49fc-11eb-952a-a84c7cb67adf.png)

I'm stuck to this diagnostic and don't know how to investigate further. Maybe it is not an Alacritty related problem and maybe you can help me fix it.
Let me know if i can give you more informations on my config or anything else like logs etc.

Thanks for the great job you'r doing with this project ! :smile:

**Comment by chrisduerr** [comment]
That does sound like it's an issue with Alacritty.

**Comment by chrisduerr** [comment]
Upstream tracking issue: https://github.com/rust-windowing/winit/issues/1810.

**Comment by J-Kappes** [comment]
I have the same problem on Fedora Gnome Xorg but when I  use `setxkbmap` to set my keymap, the problem disappears for the rest of the session or until I use Gnome settings to change keyboard layouts again.

**Comment by raulbethencourt** [comment]
Hi,
Is this solve, I have same problem with Ubuntu 22.04. I'm setting greater and less to menu key and it's working in all app exept alacritty.
Thanks

**Comment by kchibisov** [comment]
On the latest master it likely should be solved.

**Comment by raulbethencourt** [comment]
Thanks

**Comment by deft01** [comment]
Thanks, I will test it asap

**Comment by diegoximenes** [comment]
I've tried with alacritty 0.13.2 (bb8ea18e) and the problem persists.

Any updates on that?
