### ISSUE TITLE
Sometimes alacritty doesn't fully render output

### ISSUE THREAD

**Issue by maximbaz** [alacritty/alacritty#540]
Quite often alacritty doesn't finish rendering the output, it is reproducible even after executing the same command over and over again. When it's stuck, if I hit Enter, this will cause it to refresh window, but until I do anything inside the window, it will remain like that.

It's best described with a gif:

![alacritty](https://cloud.githubusercontent.com/assets/1177900/25645462/9866ced4-2fae-11e7-987f-1389363ae17d.gif)

It's not the same as #459, as here window is always focused.

System info: Arch, i3, https://github.com/jwilm/alacritty/commit/f298e0455ab549aac1835ba59467ce06111b9bc9 installed via AUR.

**Comment by jwilm** [comment]
@maximbaz  thanks for the report!

This is a bummer; I thought we had squashed that issue last year before release. Did this start recently for you?

**Comment by maximbaz** [comment]
Well, to be honest I was waiting for glyph offset to be merged, so I only started using alacritty yesterday.

I wanted to do a git bisect, but I can't build almost any old commits, either rust language changes or something else.

I managed to build e0980df from 2 months ago, and there the issue exists.

I should also mention that I removed my custom config and the issue still persists, so it is not a config problem.

**Comment by iv597** [comment]
Affects me as well. As seen in the attached picture, the bottom row of neovim is about 25% cut off for me.

Installed from AUR:
```
local/alacritty-git 0.1.0.492.g6659810-1
    A cross-platform, GPU enhanced terminal emulator
```

Window manager is herbstluft if it makes any difference.

![1493838893](https://cloud.githubusercontent.com/assets/799439/25677255/da5b38fa-300a-11e7-899d-ec7bdaf94005.png)

**Comment by jwilm** [comment]
Would one of you mind trying to build from git, directly? I haven't been able to repro this, and you are both building from AUR.

**Comment by maximbaz** [comment]
I did that already, when I mentioned that I reproduced the issue on a 2 month old commit https://github.com/jwilm/alacritty/commit/e0980df48ef50ddb48021d9375ef005eac268b7e.

At that time I also built the `master` from git, and both times I could reproduce it.

And by "built" I mean I cloned the repo and ran `cargo build --release`. This is what AUR is doing anyway, it is cloning repo and running this one command.

**Comment by jwilm** [comment]
@maximbaz ah, thanks for clarifying.

Since I'm unable to repro at this point, I'll try staring at the code for a bit for anything obviously wrong.

@iv597 I just realized you're commenting on a separate issue. We've got at least 1 ticket open for it: #279.

**Comment by maximbaz** [comment]
Thanks! Is there anything I could get for you? Running in debug mode, logs, anything that could help?
We could also arrange a screen sharing if you want 🙂

**Comment by jwilm** [comment]
@maximbaz thanks for the offer, but nothing has come to mind. Last time the bug was "fixed", it was a race condition between the parser thread and render thread. Would need to add some logging to make such a thing show up in the first place.

I will probably ask you to try out a branch at some point with either logging like that or a candidate fix.

**Comment by maximbaz** [comment]
This issue is very annoying and happens quite often, I tried to investigate it. Found the old issue you were referring to (#29), the code in the referenced commits seems reasonable to me.

And then I found something curious. When I avoid the `--release` flag to `cargo build`, the bug does not reproduce! I usually can reproduce the issue within 1 minute on the release build, but not on the debug build.

@jwilm am I right to assume that there is no logic in alacritty itself that depends on whether it is debug or release build? So it must be some unfortunate compiler optimization?

**Comment by jwilm** [comment]
@maximbaz that's right; no code dependent on build type. Which version of the Rust compiler are you using? `rustc -V`

**Comment by maximbaz** [comment]
`rustc 1.17.0`

**Comment by maximbaz** [comment]
Digging deeper, making changes below to `[profile.release]` section of `Cargo.toml` (one at a time) and observing the results of `cargo build --release`:

- `lto = false` -- no effect
- `opt-level = 2` -- no effect (3 is the default value for release)
- `opt-level = 1` -- 🎉 bug is not reproducing

So, I guess this is a hard proof that compiler optimization is somehow influencing the behavior.

How can we go from here? It would be unfortunate to disable the optimizations for everyone, and yet I'm sure I am not (or will not) be the only one affected. This is also not an easy job to describe the bug for the compiler team 🙂

For now I'll be manually adding `opt-level = 1` as the last line of `Cargo.toml` before every upgrade.

**Comment by jonhoo** [comment]
@maximbaz my guess is that the optimization level only affects this in the sense that it makes the code run faster, and therefore triggers a race condition more often (or at all).

I've seen this occasionally (using git build), though for me it's usually individual characters inside neovim. In particular, it seems to happen to non-ASCII characters like ø. Not sure if that is of any help at all.

**Comment by maximbaz** [comment]
I agree, it is more probable that the race condition is on alacritty's side than it is a bug in the compiler itself.

**Comment by gslavin** [comment]
I have been having the same issue.  The oldest commit I can still build  (4e9a307bed50fc02f101eb6cbfa4d39283dd6b8c from December 12th 2016) still reproduces the issue so I don't think its a recent regression.  The issue reproduces consistently on both debug and release builds, but it's harder to reproduce on a debug build.  I've also tried both the stable (1.18) and nightly compiler, and the issue reproduces on both.

It appears to be a subtle race condition in alacritty based the various build configurations I've tested.

**Comment by maximbaz** [comment]
I've replaced my laptop and I cannot reproduce this issue anymore (don't have access to the old laptop). It still has an Intel GPU, although a different model. 

The only software difference I can think of is that I do not have [xf86-video-intel](https://www.archlinux.org/packages/extra/x86_64/xf86-video-intel/) (X.org Intel video driver). It didn't work properly on the new laptop, and as I learned it is [often not recommended](https://wiki.archlinux.org/index.php/intel_graphics) to install.

@gslavin out of curiosity, what kind of hardware and OS do you use? If you happen to be on Arch, do you have xf86-video-intel installed and can you reproduce the issue after removing this driver and rebooting?

**Comment by gslavin** [comment]
I'm running Ubuntu 16.04.2 LTS on a late 2011 MacBook Pro, so the issue isn't because of the mentioned driver.

For me, this issue only occurs if my terminal is maximized.  If I use a smaller window size (literally anything besides maximized), I cannot reproduce the issue.

**Comment by snizovtsev** [comment]
This bug annoys me about every 2 minutes on my system.

Here is tty vs screen records: https://asciinema.org/a/HCMenCXrVJ5Y4JTrJsUV4mc3s vs https://yadi.sk/d/Tr7RrDBV3RaZMh. Look at the moment of switching between numbers 36-38. Asciinema correctly renders 36->37->38 transition but alacritty skips frame 37.

Sysinfo:
Alacritty Release b396a9 compiled with rustc 1.23.0
Ubuntu 16.04 with mainline 4.14.13-041413-generic kernel (other versions affected too)
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 17.2.4
OpenGL core profile shading language version string: 4.50
OpenGL version string: 3.0 Mesa 17.2.4
OpenGL shading language version string: 1.30
OpenGL vendor string: Intel Open Source Technology Center

**Comment by snizovtsev** [comment]
Seems replacing xf86-video-intel with modesetting driver fixes this issue.

**Comment by adambair** [comment]
I just started getting this for some reason (not sure, maybe a few weeks/months ago). I'm using Arch and i3-gaps. Never had this issue on Gnome for whatever reason...

```
$ alacritty --version
alacritty 0.2.0
```
```
$ rustc -V
rustc 1.29.1
```

**Comment by andys8** [comment]
I'm going to try `opt-level = 1`: https://github.com/jwilm/alacritty/issues/540#issuecomment-304479048
This is weird. I never noticed it before updating to 0.3.2. Now this issue bothers me multiple times a day.

**Comment by chrisduerr** [comment]
While doing some refactoring for the event loop 2.0 rework, I found an interesting mismatch in constants which might be responsible for this.

The PTY reader buffer is defined with a size of `0x1_000` here:
https://github.com/jwilm/alacritty/blob/master/alacritty_terminal/src/event_loop.rs#L332

However, the maximum number of bytes which can be read into this buffer is defined as `0x10_000` a bit farther down:
https://github.com/jwilm/alacritty/blob/master/alacritty_terminal/src/event_loop.rs#L234

I personally can't reproduce this issue, however if anyone who can could recompile Alacritty in release mode, setting both of these values to `0x10_000`, that would be a huge help. I'd imagine that could solve this problem.

**Comment by AXGKl** [comment]
@chrisduerr 

```diff
            let mut state = state.unwrap_or_else(Default::default);
-            let mut buf = [0u8; 0x1000];
+            let mut buf = [0u8; 0x1_0000];
```
did not fix it, sadly.

After build I get this
 
```bash
root@localhost alacritty]# target/release/alacritty -V
alacritty 0.3.2 (f2b1bfd)
```
and my test is to repeatedly clone a repo:
```
[root@localhost alacritty]# cat /root/try
 while true; do rm -rf dotfiles_mac/; git clone git@gitlab.axiros.com:klessinger/dotfiles_mac.git; done
[root@localhost alacritty]# target/release/alacritty -e /root/try  
```
fail mode is  it hangs after 2, 3 loops and continues including a dump of the complete buffer after any stdin event (keypress).


My setup is fedora30 in vmware fusion with 3D Graphics Accel. enabled (OpenGL3.3) 
=> should be reproducable, with a VMWare Fusion Test License.
HW: MBPro 2015 13''.

And, for what it's wort: I can get rid of the error by switching 3D Graphics off and set iomem=relaxed in grub.

**Comment by chrisduerr** [comment]
@AXGKl This sounds like you're talking about #2217, not this issue?

Are you aware that this is about Alacritty actually completely swallowing output, never rendering it? So instead of rendering `1 2 3 4 5`, this bug means Alacritty sometimes renders `1 2 5`.

**Comment by eau-u4f** [comment]
I have the same issue happening, from time to time, not refreshing until I press a key.
alacritty 0.3.3 / OpenBSD 6.5

**Comment by chrisduerr** [comment]
It might be interesting to see if this can be recorded as a ref test. So when starting Alacritty with `alacritty --ref-test` it should output an `alacritty.recording` file which should print exactly the same stuff that was received during recording.

I'm curious if `cat`ing that file would show the same issue or not. If it's broken in the ref test, chances are that there might be an issue in the parser, otherwise it's likely more torwards the rendering stage.

**Comment by eau-u4f** [comment]
hey, I just did the test, the first 2-3 cat commands, just output the result and wait for next command, the 4th one just start scrolling indefinitely, recording even more etc...

is that what you are expecting?

**Comment by eau-u4f** [comment]
on my own I did not find a way to reproduce the behaviour, it happens regularly, I can never spot on what exactly triggers it, often it's on running command where I am waiting for some output coming out during the process and the end of the command, like a tar and you believe the command stalls, but pressing enter, just refresh and display the missing part.. which was finished minutes ago, I'll try again to find

**Comment by kchibisov** [comment]
> often it's on running command where I am waiting for some output coming out during the process and the end of the command, like a tar and you believe the command stalls, but pressing enter, just refresh and the missing part.

From this comment I think you're experiencing this #2217 bug, does mouse move fixes the issue? And you're on X11, are not you?

**Comment by eau-u4f** [comment]
As far as i remember when it happens, moving the mouse does not change anything, I need to press a key in the focussed windows to make it "spit out" the remaining part.

I do not experience #2217 , there is no "lag" of one key appearing after a press a new or such as described in the #2217  issue.

As said previously, alacritty 0.3.3, OpenBSD 6.5 release / amd64, so yes X11.

**Comment by kchibisov** [comment]
Oh, sorry I've misread your comment. You've said that the issue only happens in the end of the output of the long running commands and not when you're have long running command (#2217 is about continues output to a terminal on X11). So the thing that you can't repro it with mouse move just proves, that it's a different issue.

**Comment by eau-u4f** [comment]
I mainly say long running commands, because i ran a lot of those recently (while trying alacritty as a daily driver terminal) and i was waiting thinking that the command was stalled when it was just not refreshed, but I'll try to narrow or find a situation where it happens...

**Comment by jwilm** [comment]
I encountered a similar behavior recently where a program using cursor movements to update a real-time display in the normal (non alt screen) would sometimes result in missing output until <kbd>Enter</kbd> (or perhaps others) was pressed.

I believe that was with alacritty 0.3.3 (a39459e).

I'll watch out for a recurrence but it's happened precisely once for me.

**Comment by edubart** [comment]
The same behavior happens often for me (Archlinux, Intel GPU and Alacritty 0.3.3). Pressing any key or moving the mouse the missing output appears. Furthermore the issue is more frequent when all my CPU cores are near 100% usage (almost certainly).

The following testing command always triggers the issue for me if all my CPU cores are at 100%:
```
for i in `seq 1 100`; do sleep 0.1 && echo -n a; done; echo
```
Usually the output stop refreshing after the first 3-5 'a', then pressing any key or moving the mouse output refreshes. When my CPU is not being used it almost never happens.

**Comment by chrisduerr** [comment]
@edubart What you're describing is a different issue, see #2217. This is already fixed in #2438, though that's still waiting for some upstream changes.

**Comment by K41eb** [comment]
I can reproduce this issue very reliably.

I just made an Arch VM with Virtualbox, installed lightdm, i3-gaps, xorg stuff etc ... and every single time I use `pacman -S` commands Alacritty will start displaying the loading bars and then suddenly stop, moving the mouse doesn't do anything for me but pressing enter appears to make Alacritty resume rendering. In a 1m install like firefox it happens ~20 times. Sometimes it even happens before the password prompt (for `sudo pacman ... `).

alacritty 0.3.3-3

**Comment by chrisduerr** [comment]
@K41eb That issue is fixed in the latest master.

**Comment by hoshsadiq** [comment]
When will a new release be put out that includes this fix?

**Comment by vidurb** [comment]
I've encountered this issue consistently for a while. I usually rebuild alacritty from master every week or two to check if it's been resolved. When I went through that process right now, I thought of testing for the bug with the default config rather than my own custom config. During that process, I noticed that at least in my environment, the incomplete output rendering only happens when the `decorations` config value is set to `none`. I thought I would post my results here in case it helps in debugging the issue. I'm running the latest master (`8abca441827788d48de49d3552735cdd0999379e`) on Ubuntu 19.10 and kernel 5.3.0. 

Ironically, being able to disable window decorations is (for me) the killer feature that kept me rebuilding and testing alacritty every week :sweat_smile:

**Comment by chrisduerr** [comment]
Even with decorations disabled, I've never encountered this issue myself before.

It also seems very unlikely that it is the cause of this bug, so it's probably more of a coincidence I'd assume.

**Comment by aendeavor** [comment]
I had / still have the same issue. But this insight could be helpful:

### Compositors for window managers

In my case, when running [_Compton_](https://linux.die.net/man/1/compton), _Alacritty_ will show exactly the behavior mentioned above. When [_Compton_](https://linux.die.net/man/1/compton) is not running, everything works smoothly.

As I've read, this and related issue are related to [_Xorg_](https://wiki.archlinux.org/index.php/Xorg). So a compositor interfering would make sense.

### Further investigation

Maybe other compositors will do fine - one could try [_Picom_](https://wiki.archlinux.org/index.php/Picom), but as a fork of [_Compton_](https://linux.die.net/man/1/compton), there is a chance this happens too. If there are other compositors, one could / should give them a try. It'd be a shame not to be able to combine _Alacritty_ and a compositor.

I will play with [_Compton_](https://linux.die.net/man/1/compton)'s settings to figure out if there is a setting that interferes.

### Tested on

This was tested on **alacritty 0.4.1** and on **alacritty 0.5.0-dev (13eb50d)**.

**Comment by chrisduerr** [comment]
Closing as a duplicate of #824. I'm not sure why this has been kept around for so long since it seems very clearly to be the same issue. I believe I originally thought that the output was partially incorrect, but it seems like it's just freezing the redraw just like the other issue.
