### ISSUE TITLE
Building with cargo fails, unable to run custom build command for `servo-fontconfig-sys`

### ISSUE THREAD

**Issue by Druva-D** [alacritty/alacritty#5564]
**System**
OS: Ubuntu
Version: 20.04 LTS

**Logs**
`cargo build --release`
```
   Compiling servo-fontconfig-sys v5.1.0
error: failed to run custom build command for `servo-fontconfig-sys v5.1.0`

Caused by:
  process didn't exit successfully: `/home/user/Documents/alacritty/target/release/build/servo-fontconfig-sys-3a4fc4cb44fe63f6/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=FONTCONFIG_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=FONTCONFIG_STATIC
  cargo:rerun-if-env-changed=FONTCONFIG_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at '`"pkg-config" "--libs" "--cflags" "fontconfig" "fontconfig >= 2.11.1"` did not exit successfully: exit status: 1
  --- stderr
  Package fontconfig was not found in the pkg-config search path.
  Perhaps you should add the directory containing `fontconfig.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'fontconfig' found
  Package fontconfig was not found in the pkg-config search path.
  Perhaps you should add the directory containing `fontconfig.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'fontconfig' found
  ', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/servo-fontconfig-sys-5.1.0/build.rs:34:17
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:517:5
     1: std::panicking::begin_panic_fmt
               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:460:5
     2: build_script_build::main
               at ./build.rs:34:17
     3: core::ops::function::FnOnce::call_once
               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ops/function.rs:227:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I installed all the dependencies for ubuntu specified [here](https://github.com/alacritty/alacritty/blob/master/INSTALL.md#dependencies)

**Comment by sarmong** [comment]
@chrisduerr  And how to install it for Ubuntu 20.04?

**Comment by kchibisov** [comment]
The underlying building issue was resolved long time ago, so building from source should work.

**Comment by sarmong** [comment]
I just tried, have the same problem.

**Comment by kchibisov** [comment]
That's strange, do you have all dependencies installed mentioned in INSTALL.md?

**Comment by kchibisov** [comment]
If you try running `pkg-config --libs --cflags fontconfig` what do you get?

**Comment by sarmong** [comment]
For both I get 
```
Package fontconfig was not found in the pkg-config search path.
Perhaps you should add the directory containing `fontconfig.pc'
to the PKG_CONFIG_PATH environment variable
No package 'fontconfig' found
```

**Comment by kchibisov** [comment]
Yeah, you should find what provides fontconfig pkg-config package on your system... Maybe ubuntu requires reloading env. You could try searching for `fontconfig.pc`.

**Comment by sarmong** [comment]
I have a file at `/usr/lib/x86_64-linux-gnu/pkgconfig/fontconfig.pc`. How can I make it work?

**Comment by sarmong** [comment]
So.

- I have symlinked `/usr/lib/x86_64-linux-gnu/pkgconfig/fontconfig.pc` to `/usr/share/pkgconfig`, because this seems to be the path `pkgconfig` looks up by default.
- I didn't work.
- I checked the paths to other packages by running `pkg-config --libs --cflags [package]`
- They all pointed to `linuxbrew`, which is weird
- I ran `brew install fontconfig` and now `pkg-config` can find this package
- cargo build succeeds

Apparently, Brew somehow messes up pkg-config.

**Comment by amanahuja** [comment]
I had the same issue as @sarmong with `fontconfig`. 

(I am on Ubuntu, I installed all the dependencies listed as required in the documentation. Happy to provide info on my setup.)

Problem was resolved, as Sarmong suggested, by installing fontconfig using brew. After that, `cargo install alacritty` works.

**Comment by jagibson** [comment]
Same issue.  I had installed rust via brew.  Apparently if you do so you must also install fontconfig via brew.  Might be worth updating the INSTALL.md file to reflect that.

**Comment by eugenevd** [comment]
I'm on ubuntu and wasn't willing to install brew to solve this issue as suggested, doesn't make sense to me.

Using apt to install the dependencies didn't resolve properly and I used aptitude instead to fix:

`sudo aptitude install libfontconfig1-dev libfontconfig`

Posting here hoping it might help someone in future,

**Comment by karlpothast** [comment]
Try setting your TARGET env var with the host value from the output "rusct -vV" then update rustc with "rustup update". You may have to restart vscode or whatever IDE you're using.

target=rustc -vV | sed -n 's|host: ||p'
export TARGET=$target
rustup rustc

**Comment by zachfeldman** [comment]
For anyone who finds this in the future without Linux brew or aptitude, I fixed it by just installing one package:
`udo apt install libfontconfig1-dev`

**Comment by kenoss** [comment]
`fontconfig-devel` for fedora resolved it for me.

**Comment by GrantBirki** [comment]
I had an issue with running `linuxbrew` on my ubuntu system.

Running `export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig` after doing a `brew install fontconfig` fixed it for me

**Comment by montvid** [comment]
Still experiencing the problem with ubuntu 23.10 thanks for the comments that fix this.

**Comment by ClashTheBunny** [comment]
This is a philosophical question if you have linuxbrew insalled, but, as long as you have libfontconfig-dev, pkg-config from your distribution should work.  The problem is that linuxbrew always puts itself before your distribution. If you run `which pkg-config` it should show you which one you're using:

```
which pkg-config
/home/randall/.linuxbrew/bin/pkg-config
```

If this is the case, you can always unlink pkg-config while you install things that you don't want to build with linuxbrew:

```
$ brew unlink pkgconfig
Unlinking /home/randall/.linuxbrew/Cellar/pkgconf/2.3.0_1... 16 symlinks removed.
$ which pkg-config
/usr/bin/pkg-config
$ cargo install alacritty
...........snip........
$ brew link pkgconfig
```
