### ISSUE TITLE
Issues with Rosetta and Homebrew -- ARM default prefix

### ISSUE THREAD

**Issue by uajqq** [alacritty/alacritty#5698]
Trying to install commands under Homebrew produces the following error:

```
> brew update
Already up-to-date.
> brew upgrade
Error: Cannot install under Rosetta 2 in ARM default prefix (/opt/homebrew)!
To rerun under ARM use:
    arch -arm64 brew install ...
To install under x86_64, install Homebrew into /usr/local.
> brew install openssl
Error: Cannot install under Rosetta 2 in ARM default prefix (/opt/homebrew)!
To rerun under ARM use:
    arch -arm64 brew install ...
To install under x86_64, install Homebrew into /usr/local.
```

This error does not appear under other terminal emulators, like Mac built-in or iTerm 2. Running install under `arch -arm64 brew install` sometimes works but sometimes throws the same error.

### System

OS: MacOS (M1 chip) Monterey beta 12.2
Version: alacritty 0.9.0 (fed349a)

### Logs

```
Created log file at "/var/folders/9d/tb0bw9f11056r9ftyqwxhfyw0000gn/T/Alacritty-16034.log"
[2021-12-18 11:06:29.464353000] [DEBUG] [alacritty] Using environment locale: en_US.UTF-8
[2021-12-18 11:06:29.465738000] [INFO ] [alacritty] Welcome to Alacritty
[2021-12-18 11:06:29.465788000] [INFO ] [alacritty] Configuration files loaded from:
                                                      "/Users/***/.config/alacritty/alacritty.yml"
[2021-12-18 11:06:29.493268000] [DEBUG] [alacritty] Estimated DPR: 2
[2021-12-18 11:06:29.493521000] [DEBUG] [alacritty] Estimated window size: None
[2021-12-18 11:06:29.493550000] [DEBUG] [alacritty] Estimated cell size: 16 x 34
[2021-12-18 11:06:29.563924000] [INFO ] [alacritty] Device pixel ratio: 2
[2021-12-18 11:06:29.567626000] [INFO ] [alacritty] Initializing glyph cache...
[2021-12-18 11:06:29.587784000] [INFO ] [alacritty] ... finished initializing glyph cache in 0.020120875s
[2021-12-18 11:06:29.587873000] [INFO ] [alacritty] Cell size: 16 x 34
[2021-12-18 11:06:29.587893000] [INFO ] [alacritty] Padding: 10 x 10
[2021-12-18 11:06:29.587906000] [INFO ] [alacritty] Width: 1600, Height: 1200
[2021-12-18 11:06:29.588877000] [INFO ] [alacritty] PTY dimensions: 34 x 98
[2021-12-18 11:06:29.593509000] [INFO ] [alacritty] Initialisation complete
[2021-12-18 11:06:29.610415000] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['1','2',],['7',],] at line 947
```

**Comment by chrisduerr** [comment]
Should be fixed with next release.

**Comment by brainard52** [comment]
> Should be fixed with next release.

To clarify, does this mean Alacritty will be getting an M1 native build?

**Comment by notDavid** [comment]
@chrisduerr Which issue # will fix this? So we can follow... Thank you!

**Comment by mustevenplay** [comment]
@brainard52 

> > Should be fixed with next release.
> 
> To clarify, does this mean Alacritty will be getting an M1 native build?

You can already make a native build. If you execute "make app" on the repo folder, it will output an Alacritty.app, native for M1.
Happy coding!

**Comment by brandc87** [comment]
@mustevenplay 

> You can already make a native build. If you execute "make app" on the repo folder, it will output an Alacritty.app, native for M1.
Happy coding!

Running under built-in terminal runs fine.

OS: MacOS (M1 Max chip) Monterey 12.1
Version: alacritty 0.11.0-dev

I've built a native build from the repo and this issue still exists. Error output from ```brew install postgres```:

```Error: Cannot install under Rosetta 2 in ARM default prefix (/opt/homebrew)!                                     │Counting objects: 100% (10/10), done.
To rerun under ARM use:                                                                                          │Delta compression using up to 10 threads
    arch -arm64 brew install ...                                                                                 │Compressing objects: 100% (6/6), done.
To install under x86_64, install Homebrew into /usr/local.

**Comment by mulholo** [comment]
> @mustevenplay
> 
> > You can already make a native build. If you execute "make app" on the repo folder, it will output an Alacritty.app, native for M1.
> > Happy coding!
> 
> Running under built-in terminal runs fine.
> 
> OS: MacOS (M1 Max chip) Monterey 12.1 Version: alacritty 0.11.0-dev
> 
> I've built a native build from the repo and this issue still exists. Error output from `brew install postgres`:
> 
> ```
> To rerun under ARM use:                                                                                          │Delta compression using up to 10 threads
>     arch -arm64 brew install ...                                                                                 │Compressing objects: 100% (6/6), done.
> To install under x86_64, install Homebrew into /usr/local.
> ```

Out of curiosity, what does running `arch` give you?
